#!/bin/bash
cd ..

# CUDA_VISIBLE_DEVICES=1 python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot11 --emb_model gpt --batch_size 512 --beta -1 --num_epochs 300 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adagrad --cond_vars xyte --do_recon_t False --lr 5e-5 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode linear --call_kl -1 --use_mmd_reg True --beta_mmd 10 --mmd_reg_mode exp --gamma_ze 0.001 --dim_h "[512]" --dim_h_aux "[512]" --dim_h_q "[1024,512]" --dim_h_t "[512]" --use_lr_scheduler False --use_lr_warmup False --use_loss_weight True &
# CUDA_VISIBLE_DEVICES=2 python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot21 --emb_model gpt --batch_size 512 --beta -1 --num_epochs 300 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adagrad --cond_vars xyte --do_recon_t False --lr 5e-5 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode linear --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h "[512]" --dim_h_aux "[512]" --dim_h_q "[1024,512]" --dim_h_t "[512]" --use_lr_scheduler False --use_lr_warmup False --use_loss_weight True &
# CUDA_VISIBLE_DEVICES=3 python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot31 --emb_model gpt --batch_size 512 --beta -1 --num_epochs 300 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adagrad --cond_vars xyte --do_recon_t False --lr 5e-5 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode linear --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h "[512]" --dim_h_aux "[512]" --dim_h_q "[1024,512]" --dim_h_t "[512]" --use_lr_scheduler False --use_lr_warmup False --use_loss_weight True &
# CUDA_VISIBLE_DEVICES=4 python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot41 --emb_model gpt --batch_size 512 --beta -1 --num_epochs 300 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adagrad --cond_vars xyte --do_recon_t False --lr 5e-5 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode linear --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h "[512]" --dim_h_aux "[512]" --dim_h_q "[1024,512]" --dim_h_t "[512]" --use_lr_scheduler False --use_lr_warmup False --use_loss_weight True &
# CUDA_VISIBLE_DEVICES=5 python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot51 --emb_model gpt --batch_size 512 --beta -1 --num_epochs 300 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adagrad --cond_vars xyte --do_recon_t False --lr 5e-5 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode linear --call_kl -1 --use_mmd_reg True --beta_mmd 5 --mmd_reg_mode exp --gamma_ze 0.001 --dim_h "[512]" --dim_h_aux "[512]" --dim_h_q "[1024,512]" --dim_h_t "[512]" --use_lr_scheduler False --use_lr_warmup False --use_loss_weight True &
# CUDA_VISIBLE_DEVICES=6 python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot61 --emb_model gpt --batch_size 512 --beta -1 --num_epochs 300 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adagrad --cond_vars xyte --do_recon_t False --lr 5e-5 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode linear --call_kl -1 --use_mmd_reg True --beta_mmd 10 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h "[512]" --dim_h_aux "[512]" --dim_h_q "[1024,512]" --dim_h_t "[512]" --use_lr_scheduler False --use_lr_warmup False --use_loss_weight True &
# CUDA_VISIBLE_DEVICES=7 python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot71 --emb_model gpt --batch_size 512 --beta -1 --num_epochs 300 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adagrad --cond_vars xyte --do_recon_t False --lr 5e-5 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode linear --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h "[512]" --dim_h_aux "[512]" --dim_h_q "[1024,512]" --dim_h_t "[512]" --use_lr_scheduler False --use_lr_warmup False --use_loss_weight True &

CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot191 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xyte --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[128,512]' --dim_h_aux '[512,1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot291 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xyt --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[128,512]' --dim_h_aux '[512,1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot391 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xy --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[128,512]' --dim_h_aux '[512,1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot491 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xyte --do_recon_t False --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[128,512]' --dim_h_aux '[512,1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot591 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xyt --do_recon_t False --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[128,512]' --dim_h_aux '[512,1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot691 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xy --do_recon_t False --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[128,512]' --dim_h_aux '[512,1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot791 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xyte --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[128,512]' --dim_h_aux '[512,1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --lr_scheduler cosine --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot891 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xyte --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[128,512]' --dim_h_aux '[512,1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler False --lr_scheduler none --use_lr_warmup False --use_loss_weight False &
sleep 5

CUDA_VISIBLE_DEVICES=1 python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot191 &
CUDA_VISIBLE_DEVICES=2 python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot291 &
CUDA_VISIBLE_DEVICES=3 python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot391 &
CUDA_VISIBLE_DEVICES=4 python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot491 &
CUDA_VISIBLE_DEVICES=5 python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot591 &
CUDA_VISIBLE_DEVICES=6 python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot691 &
CUDA_VISIBLE_DEVICES=7 python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot791 &
CUDA_VISIBLE_DEVICES=1 python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot891 &
sleep 5

CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot192 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xyte --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[512]' --dim_h_aux '[1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot292 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xyt --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[512]' --dim_h_aux '[1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot392 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xy --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[512]' --dim_h_aux '[1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot492 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xyte --do_recon_t False --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[128,512]' --dim_h_aux '[1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot592 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xyt --do_recon_t False --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[128,512]' --dim_h_aux '[1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot692 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xy --do_recon_t False --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[128,512]' --dim_h_aux '[1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot792 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xyte --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[512]' --dim_h_aux '[1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler True --lr_scheduler cosine --use_lr_warmup False --use_loss_weight False &
CUDA_VISIBLE_DEVICES=1 nohup  python run_crl.py --save_weights True --train_w_all True --early_stop_patience 30 --exp_id shot892 --emb_model gpt --batch_size 256 --beta -1 --num_epochs 1000 --input_mode add --dataset mgsm --dim_emb 1536 --dim_latent 64 --optim adamw --cond_vars xyte --lr 1e-4 --wd 1e-2 --kl_beta_k 1e-2 --kl_beta_mode logistic --call_kl -1 --use_mmd_reg True --beta_mmd 1 --mmd_reg_mode sigmoid --gamma_ze 0.001 --dim_h '[512]' --dim_h_aux '[1024]' --dim_h_q '[1024,512,128,64]' --dim_h_t '[128,512]' --use_lr_scheduler False --lr_scheduler none --use_lr_warmup False --use_loss_weight False &
sleep 5

CUDA_VISIBLE_DEVICES=1 nohup python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot192 &
CUDA_VISIBLE_DEVICES=2 nohup python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot292 &
CUDA_VISIBLE_DEVICES=3 nohup python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot392 &
CUDA_VISIBLE_DEVICES=4 nohup python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot492 &
CUDA_VISIBLE_DEVICES=5 nohup python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot592 &
CUDA_VISIBLE_DEVICES=6 nohup python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot692 &
CUDA_VISIBLE_DEVICES=7 nohup python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot792 &
CUDA_VISIBLE_DEVICES=1 nohup python infer_latent_z.py --dataset mgsm --batch_size 512 --save_results True --is_oop True --emb_model gpt --exp_id shot892 &
sleep 5